baseurl = "https://kibou811.github.io/kibolog/"
title = "kibolog"
author = "KIBOU811"
canonifyurls = true
paginate = 3
theme = "minimo"
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"